USE [master]
GO

/****** Object:  Database [Calidad]    Script Date: 04/10/2017 6:28:06 p. m. ******/
DROP DATABASE [Calidad]
GO

/****** Object:  Database [Calidad]    Script Date: 04/10/2017 6:28:07 p. m. ******/
CREATE DATABASE [Calidad]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Calidad].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Calidad] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Calidad] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Calidad] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Calidad] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Calidad] SET ARITHABORT OFF 
GO

ALTER DATABASE [Calidad] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Calidad] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Calidad] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Calidad] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Calidad] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Calidad] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Calidad] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Calidad] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Calidad] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Calidad] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Calidad] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Calidad] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Calidad] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Calidad] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [Calidad] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Calidad] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Calidad] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Calidad] SET RECOVERY FULL 
GO

ALTER DATABASE [Calidad] SET  MULTI_USER 
GO

ALTER DATABASE [Calidad] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Calidad] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Calidad] SET  READ_WRITE 
GO


